# Generated by Django 5.0.1 on 2024-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_discription',
            new_name='receipe_description',
        ),
    ]
